title: K. Huang's Matrix
author: K. Huang
email: kunhuang@connect.hku.hk
description: >- # this means to ignore newlines until "baseurl:"
  viva la vida!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  hku

minima:
  date_format: "%b %-d, %Y"


header_pages:
  - about.html

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: "articles"
    values:
      layout: "article"
      comments: true
      article: true